### ISSUE TITLE
F01 Find the temperature of the eye corner and the nose tip.

### ISSUE THREAD

**Issue by kmm94** [rubenbaskaran/MasterThesisApp#1]
As a user I want to find the temperature of the eye corner and the nose tip, so that I can calculate the gradient. 

- [ ] Find the correct pixel.
- [ ] Get the temperture of a pixel.
- [ ] Calculate the gradient either (eyeRight+eyeLeft/2)-nose or choose an eye-nose
